repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-json
        exclude: ^(\.vscode/|\.devcontainer/)
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^custom_components/yamaha_soundbar/(yamaha_client\.(crt|key)|client\.pem)$
      - id: trailing-whitespace
        exclude: ^custom_components/yamaha_soundbar/(yamaha_client\.(crt|key)|client\.pem)$
      - id: mixed-line-ending
        args: [--fix=lf]
